### ISSUE TITLE
Can not find "./models/fetch_release_models.sh"

### ISSUE THREAD

**Issue by yildirimatcioglu** [alex011235/Colorizer-iOS#3]
Hey, inside the colorization repository I can not find "./models/fetch_release_models.sh" file. can you guys help me about it. I am not familiar with ML things. I am just an iOS Dev.

**Comment by Alex13832** [comment]
You need to switch branch to "Caffe branch" to find that file. I think the author of that project made some change but decided to keep the original project in a branch.
