### ISSUE TITLE
Color Film

### ISSUE THREAD

**Issue by Thorsten65** [alex011235/Colorizer-iOS#4]
I have an old 2min. black and white film with Animake broken down into 4000 frames. Have already created a 5th sec color film with Photoshop. Must edit every single frame. I'm still in the middle of the learning phase of Github. But at some point I'll make it ... laugh

![videoframe 30  1 16s  -- WalsumVideo 768+576 avi 25a](https://user-images.githubusercontent.com/63239824/97761087-14a3d600-1b05-11eb-890e-54d72e52dfa6.jpg)
![avideoframe 30  1 16s  -- WalsumVideo 768+576 avi 25](https://user-images.githubusercontent.com/63239824/97761106-24bbb580-1b05-11eb-8792-3854e0eda607.jpg)

**Comment by Alex13832** [comment]
Nice project. But it sounds like it will take you a lot of time to finish this. 
I think a script using the colorizing model could turn your film to color in minutes. Writing the script could take an hour or two. The result might look a little different than Photoshop.

I could add a feature to convert a film to color but it will depend on what formats iPhone support. I'll investigate.

**Comment by Thorsten65** [comment]
As I had already written, I still have a lot to learn. First I got a bit familiar with all programs like Git SDK 64bit , Git Bash , Phyton and Windows PowerShell ISE. I haven't installed Markdown yet. In the 80's I learned Basic and Qbasic. Some commands also occur here at Github, but for me this is a nail new program language. But back to the subject of color film.

Here is the original video:
https://1drv.ms/v/s!Apm7K0i_j-Ury0VzvJbwLf1Fol6H?e=u87SCH

I first converted this video to AVI format and disassembled it into thousands of frames with the program https://www.animake.de/. 

Here the black - white frames
**The frames come later. Just upload.** https://1drv.ms/u/s!Apm7K0i_j-UrgP5Dqj8r7uGgShq0MA?e=w06bZw

Here is a small video in color. my first attempt.
https://1drv.ms/v/s!Apm7K0i_j-UrzlhA8B9e3jTKOKRR?e=YAA3Fs

But I didn't like it. So I learned everything about the right rendering with "Magix Video Deluxe 2016 Plus" on Youtube. In addition, image formats such as Tiff and PDS. I then converted the whole frames in PDS format with Photoshop 2020 and edited and saved them. These stored frames are converted with IrfanView into Tiff ( width 4800 pixels / height 3600 pixels) resolution 600 dpi , bit depth 24. A frame now has a size of 
45.6 MB (47,915,306 bytes). I then rendered these large single frames to a movie.
But I think it was worth it.
https://1drv.ms/v/s!Apm7K0i_j-Ur432tpLDYatksVgZP?e=eWeLAJ

My goal is to write all this work in one script. But I'm still worlds away from it. I envy you programmers writing scripts as if it were a love letter...  Laughing.

**Comment by Alex13832** [comment]
I understand, I can add a feature to convert movies to animated images, a long series of images. I don't think I can add sound to the animation unfortunately. Here's a teaser:

![teaser](https://user-images.githubusercontent.com/9933336/98029374-b0885700-1e0f-11eb-84fe-5d5bed9081d4.gif)

The app is quite slow if I load big movies, I still need to figure out how to use more frames from a movie, right now the code just sample one frame per second. Then, If I want to create a movie of the animation, I need to be able generate the movie in some way.

**Comment by Thorsten65** [comment]
Sorry das ich mich erst jetzt melde. Privater Todesfall. Aber sieht doch schon super aus. Bin gerade dabei, meinen PC neu zu installieren. Dauert zwar, musste aber sein.
