### ISSUE TITLE
Reference to 'Ptr' is ambiguous

### ISSUE THREAD

**Issue by codaman** [alex011235/Colorizer-iOS#5]
in ImageUtils.mm

Ptr<dnn::Layer> class8_ab = net.getLayer("class8_ab");
class8_ab->blobs.push_back(pts_in_hull);
Ptr<dnn::Layer> conv8_313_rh = net.getLayer("conv8_313_rh");

I got this error.
Reference to 'Ptr' is ambiguous

**Comment by Alex13832** [comment]
Are you sure you got the latest version? I remember that I got the same problem before I added the opencv cv:: namespace to all opencv function calls.

**Comment by codaman** [comment]
ok i solved problem thank you
